<testsuite name="Mocha Tests" tests="3" failures="0" errors="1" skipped="0" timestamp="Mon, 12 Jun 2023 20:34:43 GMT" time="0.765">
<testcase classname="Sample task tests" name="execute read assembyl.cs" time="0.264"/>
<testcase classname="Sample task tests" name="execute read csproj" time="0.238"/>
<testcase classname="Sample task tests" name="execute read tests" time="0.26"><failure>should not failed

      + expected - actual

      -false
      +true
      
AssertionError [ERR_ASSERTION]: should not failed
    at Context.&#x3C;anonymous&#x3E; (tests\_suite.js:58:16)
    at process.processImmediate (node:internal/timers:476:21)</failure></testcase>
</testsuite>
